spring:
  cloud:
    gateway:
      routes:
        - id: api-microservice-one
          uri: ${microservice.one.url}
          predicates:
            - Path=/api/microservice-one/**
          filters:
            - name: CustomJwt
              args:
                jwtTokenGenerator: "#{@jwtTokenGenerator}"

        - id: api-microservice-two
          uri: ${microservice.two.url}
          predicates:
            - Path=/api/microservice-two/**
          filters:
            - name: CustomJwtPermissions
              args:
                jwtTokenGenerator: "#{@jwtTokenGenerator}"
                rolesPermissionsService: "#{@rolesPermissionsService}"

        - id: default
          uri: ${microservice.default.url}
          predicates:
            - Path=/**

logging:
  level:
    org.springframwork.cloud.gateway: ${log.level:INFO}
    org.springframwork.http.server.reactive: ${log.level:INFO}
    org.springframwork.web.reactive: ${log.level:INFO}
    reactor.ipc.netty: ${log.level:INFO}
    reactor.netty: ${log.level:INFO}